language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
sudo: false
# command to run tests
script: py.test
notifications:
  irc:
    channels:
      - "irc.hackint.eu#voc-wok"
    use_notice: true
    skip_join: true
